---
# Create the SSL certificate

- name: create self-signed SSL certs
  command: openssl req -new -newkey rsa:2048 -nodes -x509 -subj "/C=US/ST=WA/L={{ item.location }}/O={{ item.owner }}/CN={{ ansible_fqdn }}" -days 3650 -keyout {{ docker_nginx_conf_dir }}/.{{ item.name }}.key -out {{ docker_nginx_conf_dir }}/.{{ item.name }}.crt -extensions v3_ca creates={{ docker_nginx_conf_dir }}/.{{ item.name }}.crt
  with_items: ssl_certificates
  when: item.generate

- name: copy existing SSL .crt
  copy:
    content: "{{ startssl_crt }}"
    dest: "{{ docker_nginx_conf_dir }}/.{{ item.name }}.crt"
  with_items: ssl_certificates
  when: not item.generate

- name: copy existing SSL .key
  copy:
    content: "{{ startssl_key }}"
    dest: "{{ docker_nginx_conf_dir }}/.{{ item.name }}.key"
  with_items: ssl_certificates
  when: not item.generate
